name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - gitaction
    workflow_dispatch:

jobs:
  run-on-linux:
    runs-on: ubuntu-22.04
    strategy: 
      matrix: 
        target: [x86_64, aarch64]
    steps:
      - run: uname -a
      
